version: "3"
services:
#  nginx:
#      image: 'nginx:alpine'
#      ports:
#        - '8080:8080'
#      volumes:
#        - ./.docker/nginx-dev.conf:/etc/nginx/nginx.conf
#      links:
#        - node-server
  zookeeper:
      image: confluent/zookeeper
      ports:
          - "2181:2181"
      environment:
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_TICK_TIME: 2000
      restart: always
  kafka:
      image: confluent/kafka
      ports:
          - "9092:9092"
      depends_on:
        - zookeeper
      environment:
        KAFKA_ADVERTISED_HOST_NAME: kafka
        KAFKA_ADVERTISED_PORT: "9092"
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      restart: always
  node-server:
    container_name: olm-server
    restart: always
    build: .
    ports:
      - "8000:8000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    environment:
      DATABASE_URL: mongodb:27017
    command: mongod --port 27017